version: '3.8'
services:
  gcopy:
    container_name: gcopy
    build:
      context: ..
      dockerfile: build/gcopy/Dockerfile
    restart: always
    ports:
    - "3376:3376"
    env_file:
    - ./.env
    command: ["--app-key=${APP_KEY}"]

  gcopy-frontend:
    container_name: gcopy-frontend
    build:
      context: ..
      dockerfile: build/frontend/Dockerfile
    restart: always
    ports:
    - "3000:3375"
    depends_on:
    - gcopy
